### ISSUE TITLE
Graceful Trainer Cleanup upon `KeyboardInterrupt`

### ISSUE THREAD

**Issue by Averylamp** [mosaicml/composer#108]
Trainers do not cleanup properly when KeyboardInterrupted.  Should cleanup the model/possibly keep the model in a state where it can be partially trained but evaluated `.fit()` is exited early.  Probably should gracefully exit and cleanup for interactive composer users

** To reproduce
```
from composer import algorithms, trainer, Trainer
from composer.core.types import Precision

hparams = trainer.load("classify_mnist_cpu")  # loads from composer/yamls/models/classify_mnist_cpu.yaml
hparams.algorithms = algorithms.load_multiple("blurpool", "label_smoothing")

# edit other properties in the hparams object
hparams.precision = Precision.FP32
hparams.grad_accum = 2
hparams.set_datadir("~/datasets")

trainer = Trainer.create_from_hparams(hparams)
trainer.fit()

```
then CTRL-C, Keyboard Escape
then
```
trainer.fit()
```

Produces
```
>>> trainer.fit()
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 245, in _feed
    send_bytes(obj)
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 245, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
BrokenPipeError: [Errno 32] Broken pipe
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
  File "/home/avery/mosaic/composer/composer/trainer/trainer.py", line 356, in fit
BrokenPipeError: [Errno 32] Broken pipe
    self._train_loop()
  File "/home/avery/mosaic/composer/composer/trainer/trainer.py", line 488, in _train_loop
    assert isinstance(original_model, BaseMosaicModel)
AssertionError
```

**Comment by ravi-mosaicml** [comment]
Going to break this issue into two:
1. When someone issues a sigterm (via ctrl c), the training process should exit without a messy stock trace. It should be possible to checkpoint the model after a ctrl-c, and resume the model from training after such a checkpoint.

2. The trainer supports eval only (#40) and multiple calls to .fit.

I'll implement part 1 here and do part 2 in separate issues / prs.

**Comment by ravi-mosaicml** [comment]
Closing as this is no longer an issue -- we have test cases that call `.fit()` multiple times. See
https://github.com/mosaicml/composer/blob/6971d0a9eb72c30324d64a994c1f6d879d935f4a/tests/trainer/test_trainer.py#L379
