### ISSUE TITLE
Composer crashes due to DDP time-out

### ISSUE THREAD

**Issue by moinnadeem** [mosaicml/composer#179]
** Environment **
GCP A100s running `mosaicml/composer:all-0.2.4`

I get this trace-back relatively often (third time that I've seen this, so it certainly isn't a one-off error).

```
Traceback (most recent call last):
  File "/workspace/src/composer/examples/run_mosaic_trainer.py", line 47, in <module>
    main()
  File "/workspace/src/composer/examples/run_mosaic_trainer.py", line 42, in main
    trainer = Trainer.create_from_hparams(hparams=hparams)
  File "/workspace/src/composer/composer/trainer/trainer.py", line 366, in create_from_hparams
    trainer = cls(
  File "/workspace/src/composer/composer/trainer/trainer.py", line 199, in __init__
    ddp.initialize_ddp(device.ddp_backend, datetime.timedelta(seconds=ddp_timeout))
  File "/workspace/src/composer/composer/utils/ddp.py", line 205, in initialize_ddp
    dist.init_process_group(backend, timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/distributed_c10d.py", line 547, in init_process_group
    _store_based_barrier(rank, store, timeout)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/distributed_c10d.py", line 219, in _store_based_barrier
    raise RuntimeError(
RuntimeError: Timed out initializing process group in store based barrier on rank: 0, for key: store_based_barrier_key:1 (world_size=8, worker_count=7, timeout=0:00:05)
```

Do we need to increase the timeout for GCP, or is there something else going on?

**Comment by Landanjs** [comment]
I had this issue with DeepLabV3 since I was downloading pretrained weights during model initialization. A quick fix is to set `--ddp_timeout` to larger value. I'm not sure if the long-term solution is to set `--ddp_timeout` on a case by case basis or to make a more general change to ddp. cc: @jbloxham?

**Comment by jbloxham** [comment]
Assuming @moinnadeem's error is the same as @Landanjs's, the fix here is to initialize the distributed environment before doing any model or dataset initialization. That should be a quick fix. @Landanjs do you have a YAML I could use to replicate?

**Comment by Landanjs** [comment]
I'm currently working on my fork on branch `landan/ade20k_deeplabv3`, but this should hopefully be merged by the end of the week. Alternatively, I suspect setting `--model.gpt2.use_pretrained true` when using the GPT-2 yamls would result in the same issue.

**Comment by ravi-mosaicml** [comment]
Closing for now as the timeout may need to be adjusted on a per-experiment basis. If there is a better default timeout, please create a PR for that -- happy to adjust it so long as it's reasonable (i.e. probably on the order of minutes)?

**Comment by moinnadeem** [comment]
Wait, I think we should take a look at this since we're seeing a few people run into this. I know I've launched experiments only to see them fail due to a poor time-out. @Landanjs Are you still seeing this? Maybe we could both find a good timeout for us and make that a new default?

**Comment by moinnadeem** [comment]
Yeah, can do! I'm really focused on getting speedups at the moment, and then will spend time fixing a lot of the Composer bugs that I've been running into. I can take care of a lot of that stuff early February.

**Comment by Landanjs** [comment]
I can check as well when some GPUs become available

**Comment by Landanjs** [comment]
Just checking, #272 should fix this right?
