### ISSUE TITLE
Composer crashes on nightly due to an import error in FSDP

### ISSUE THREAD

**Issue by Skylion007** [mosaicml/composer#2266]
** Environment **

** To reproduce

1. Install nightly version of pytorch etc.
2. Try to run mosaicml
3. Get this error:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/hydra/_internal/instantiate/_instantiate2.py", line 92, in _call_target
    return _target_(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/composer/trainer/trainer.py", line 950, in __init__
    prepare_fsdp_module(model, optimizers, self.fsdp_config, precision, device, auto_microbatching)
  File "/usr/lib/python3/dist-packages/composer/trainer/dist_strategy.py", line 154, in prepare_fsdp_module
    from composer.trainer.mosaic_fsdp import (MosaicFullyShardedDataParallel, backward_prefetch_map, get_cpu_offload,
  File "/usr/lib/python3/dist-packages/composer/trainer/mosaic_fsdp.py", line 19, in <module>
    from torch.distributed.fsdp._utils import _contains_batchnorm, _override_batchnorm_mixed_precision
ImportError: cannot import name '_contains_batchnorm' from 'torch.distributed.fsdp._utils' (/usr/lib/python3/dist-packages/torch/distributed/fsdp/_utils.py)
```

4.
5.

**Comment by mvpatel2000** [comment]
Closing and moving offline

**Comment by edward-io** [comment]
I'm also encountering the same issue. Looks like the function was removed in https://github.com/pytorch/pytorch/pull/102010.

**Comment by mvpatel2000** [comment]
@edward-io at this time, we don't officially support pytorch nightly. We're discussing adding support for it in a better way, but it won't happen for a little bit. 

@Skylion007 is there any temporary workarounds you were able to find?

**Comment by edward-io** [comment]
@mvpatel2000 makes sense, just wanted to flag it. The latest supported torch version (2.0.1), FSDP fails:

```
│ /home/fsuser/miniconda3/lib/python3.10/site-packages/torch/distributed/fsdp/_optim_utils.py:1690 │
│ in _gather_orig_param_state                                                                      │
│                                                                                                  │
│   1687 │   ):                                                                                    │
│   1688 │   │   return optim_state                                                                │
│   1689 │                                                                                         │
│ ❱ 1690 │   gathered_state = _all_gather_optim_state(fsdp_state, optim_state)                     │
│   1691 │                                                                                         │
│   1692 │   # Unflatten state values.                                                             │
│   1693 │   for state_name, value in list(gathered_state.items()):                                │
│                                                                                                  │
│ /home/fsuser/miniconda3/lib/python3.10/site-packages/torch/distributed/fsdp/_optim_utils.py:1637 │
│ in _all_gather_optim_state                                                                       │
│                                                                                                  │
│   1634 │   for rank, object_state in enumerate(object_list):                                     │
│   1635 │   │   if rank in empty_ranks:                                                           │
│   1636 │   │   │   continue                                                                      │
│ ❱ 1637 │   │   for name, non_tensor_value in object_state.non_tensors.items():                   │
│   1638 │   │   │   curr_non_tensor_value = gathered_state.get(name, None)                        │
│   1639 │   │   │   assert (                                                                      │
│   1640 │   │   │   │   curr_non_tensor_value is None                                             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'int' object has no attribute 'items'
```

but is fixed here: https://github.com/pytorch/pytorch/issues/99079 in nightly.
