### ISSUE TITLE
`WandBLogger` fails to initialize when called twice

### ISSUE THREAD

**Issue by ez2rok** [mosaicml/composer#2348]
# Describe the Bug

I am training image classification models on Cifar100 with various `trainer` configurations, ie with different seeds, speed-up algorithms, number of epochs, etc. I want to log all of these training runs with the [WandBLogger](https://docs.mosaicml.com/projects/composer/en/latest/api_reference/generated/composer.loggers.WandBLogger.html#composer.loggers.WandBLogger). Fitting and logging the first configuration of parameters works fine. But fitting and logging the second configuration always fails, no matter what the second configuration of parameters looks like. Even when I initialize and fit the trainer twice with the same exact parameters, I get an error. It seems that something in the WandBLogger is somehow different between the first and second call of `trainer.fit()`.

Specifically, the second call to `trainer.fit()` while using the `WandBLogger` always gives me this error:
```python
---------------------------------------------------------------------------
Error                                     Traceback (most recent call last)
[<ipython-input-8-d36b8644eafa>](https://localhost:8080/#) in <cell line: 23>()
     21 
     22 # run everything
---> 23 main(params, data, train_config)

5 frames
[<ipython-input-7-1a916b60d85b>](https://localhost:8080/#) in main(params, data, train_config)
      6               # train the model
      7               trainer = get_trainer(params, data, seed, n_epochs)
----> 8               trainer.fit()

[/usr/local/lib/python3.10/dist-packages/composer/trainer/trainer.py](https://localhost:8080/#) in fit(self, train_dataloader, train_dataloader_label, train_subset_num_batches, spin_dataloaders, duration, reset_time, schedulers, scale_schedule_ratio, step_schedulers_every_batch, eval_dataloader, eval_subset_num_batches, eval_interval, device_train_microbatch_size, precision)
   1802 
   1803         self.first_batch_complete = False
-> 1804         self._train_loop()
   1805 
   1806     def close(self):

[/usr/local/lib/python3.10/dist-packages/composer/trainer/trainer.py](https://localhost:8080/#) in _train_loop(self)
   1912         # print training start
   1913         log.info('Using precision %s', self.state.precision)
-> 1914         self.logger.log_hyperparameters(
   1915             {'enabled_algorithms/' + algo.__class__.__name__: True for algo in self.state.algorithms})
   1916         assert self.state.dataloader is not None, 'dataloader is set in __init__() or fit()'

[/usr/local/lib/python3.10/dist-packages/composer/loggers/logger.py](https://localhost:8080/#) in log_hyperparameters(self, parameters)
     59     def log_hyperparameters(self, parameters: Dict[str, Any]):
     60         for destination in self.destinations:
---> 61             destination.log_hyperparameters(parameters)
     62 
     63     def log_metrics(self, metrics: Dict[str, float], step: Optional[int] = None) -> None:

[/usr/local/lib/python3.10/dist-packages/composer/loggers/wandb_logger.py](https://localhost:8080/#) in log_hyperparameters(self, hyperparameters)
    116         if self._enabled:
    117             import wandb
--> 118             wandb.config.update(hyperparameters)
    119 
    120     def log_metrics(self, metrics: Dict[str, Any], step: Optional[int] = None) -> None:

[/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/preinit.py](https://localhost:8080/#) in __getattr__(self, key)
     25     def __getattr__(self, key: str) -> Any:
     26         if not key.startswith("_"):
---> 27             raise wandb.Error(f"You must call wandb.init() before {self._name}.{key}")
     28         else:
     29             raise AttributeError

Error: You must call wandb.init() before wandb.config.update
```
The important part of the error message is the last line
```python
Error: You must call wandb.init() before wandb.config.update
```

`wandb.init()` is called in the function `WandBLogger.init()` [here](https://github.com/mosaicml/composer/blob/b6e2f55dd9f83afa2bc851a71f830c0874219fe2/composer/loggers/wandb_logger.py#L204) ; note that `WandBLogger.init()` is different from `WandBLogger.__init__()`. 

For some reason, the function  `WandBLogger.init()` is successfully called the first time we run `trainer.fit()`, but unsuccessfully called the second time we run `trainer.fit()`. I don't understand how the first call to `trainer.fit()` differs from the second call to `trainer.fit()`.

# The Notebook

To explore this further, I created a reproducible [google-colab notebook](https://colab.research.google.com/drive/13E9fnLC6a88LR2Cfyx_DeBqoGTuA_wc_?usp=sharing) with this error. 

In the notebook, I train for 1 epoch with only 4096 samples of cifar100 -- this is simply to train quickly and illustrate the error as a minimal reproducible example. (Don't forget to change the runtime type to GPU of type T4 -- these were the settings I used.) The notebook has three main parts, a function to get the data, to get the trainer, and `main` to run all of the different configurations of the trainer. 

The notebook (in psudeocode) looks something like this:
```python
	def get_trainer(params, data, seed, n_epochs):
		model = models.composer_resnet_cifar(model_name="resnet_56", num_classes=100)
		logger = WandBLogger()
		optimizer = DecoupledSGDW()
		scheduler = CosineAnnealingWithWarmupScheduler()
		trainer = Trainer(
		        model=model,
		        train_dataloader=data['train_dataloader'],
		        eval_dataloader= data['test_dataloader'],
		        device=params['device'],
		        max_duration=n_epochs,
		        optimizers=optimizer,
		        schedulers=scheduler,
		        seed=seed,
		        loggers=logger
		    )
		return trainer
```
```python
	def main(params, data, train_config):

      for seed in train_config['seeds']:
          for n_epochs in train_config['epochs']:

              # train the model
              trainer = get_trainer(params, data, seed, n_epochs)
              trainer.fit()
```
```python
	data = get_data()
	params = get_params()
	train_config = get_train_config()
	main(params, data, train_config)
```

Looking closely at the error message, the error occurs when `trainer.fit()` is called. However, I believe the cause of the error may be in `get_trainer()` which defines the `trainer` object. For more details, please look at the exact code in the notebook.

# What I've tried

1. If I do not pass the `WandBLogger` to the `trainer` object, everything works fine. This shows that the issue is 100% due to the `WandBLogger` being used.
2. Looking at the second-to-last function in the call stack, we see that the error arises when we call `WandBLogger.log_hyperparameters()`. So I tried adding
	```python
	wandb.init(**self._init_kwargs)
	```
	just before we call `wandb.config.update`. To do this, I locally edit the file `wandb_logger.py` in the colab notebook and then restarted the runtime. (This file can be found [here](https://github.com/mosaicml/composer/blob/b6e2f55dd9f83afa2bc851a71f830c0874219fe2/composer/loggers/wandb_logger.py#L117) in composer repo.) Doing this actually fixes the error! However, this is more of a bandaid-fix and doesn't really explain what is going on. 
3. To explore things further, I tried adding
	```python
	import traceback
	traceback.print_stack()
	```
	in the `WandBLogger.init()` function  [here](https://github.com/mosaicml/composer/blob/b6e2f55dd9f83afa2bc851a71f830c0874219fe2/composer/loggers/wandb_logger.py#L203) to see when this function is actually being called. Recall that `WandBLogger.init()` is where `wand.init()`, our missing function, is called. Interestingly `WandBLogger.init()` is called twice, resulting in two calls stacks. First,
	```python
	   File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
	    return _run_code(code, main_globals, None,
	  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
	    exec(code, run_globals)
	  File "/usr/local/lib/python3.10/dist-packages/ipykernel_launcher.py", line 16, in <module>
	    app.launch_new_instance()
	  File "/usr/local/lib/python3.10/dist-packages/traitlets/config/application.py", line 992, in launch_instance
	    app.start()
	  File "/usr/local/lib/python3.10/dist-packages/ipykernel/kernelapp.py", line 619, in start
	    self.io_loop.start()
	  File "/usr/local/lib/python3.10/dist-packages/tornado/platform/asyncio.py", line 195, in start
	    self.asyncio_loop.run_forever()
	  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
	    self._run_once()
	  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
	    handle._run()
	  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
	    self._context.run(self._callback, *self._args)
	  File "/usr/local/lib/python3.10/dist-packages/tornado/ioloop.py", line 685, in <lambda>
	    lambda f: self._run_callback(functools.partial(callback, future))
	  File "/usr/local/lib/python3.10/dist-packages/tornado/ioloop.py", line 738, in _run_callback
	    ret = callback()
	  File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 825, in inner
	    self.ctx_run(self.run)
	  File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 786, in run
	    yielded = self.gen.send(value)
	  File "/usr/local/lib/python3.10/dist-packages/ipykernel/kernelbase.py", line 377, in dispatch_queue
	    yield self.process_one()
	  File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 250, in wrapper
	    runner = Runner(ctx_run, result, future, yielded)
	  File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 748, in __init__
	    self.ctx_run(self.run)
	  File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 786, in run
	    yielded = self.gen.send(value)
	  File "/usr/local/lib/python3.10/dist-packages/ipykernel/kernelbase.py", line 361, in process_one
	    yield gen.maybe_future(dispatch(*args))
	  File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 234, in wrapper
	    yielded = ctx_run(next, result)
	  File "/usr/local/lib/python3.10/dist-packages/ipykernel/kernelbase.py", line 261, in dispatch_shell
	    yield gen.maybe_future(handler(stream, idents, msg))
	  File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 234, in wrapper
	    yielded = ctx_run(next, result)
	  File "/usr/local/lib/python3.10/dist-packages/ipykernel/kernelbase.py", line 539, in execute_request
	    self.do_execute(
	  File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 234, in wrapper
	    yielded = ctx_run(next, result)
	  File "/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py", line 302, in do_execute
	    res = shell.run_cell(code, store_history=store_history, silent=silent)
	  File "/usr/local/lib/python3.10/dist-packages/ipykernel/zmqshell.py", line 539, in run_cell
	    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
	  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 2975, in run_cell
	    result = self._run_cell(
	  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3030, in _run_cell
	    return runner(coro)
	  File "/usr/local/lib/python3.10/dist-packages/IPython/core/async_helpers.py", line 78, in _pseudo_sync_runner
	    coro.send(None)
	  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3257, in run_cell_async
	    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
	  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3473, in run_ast_nodes
	    if (await self.run_code(code, result,  async_=asy)):
	  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
	    exec(code_obj, self.user_global_ns, self.user_ns)
	  File "<ipython-input-8-d36b8644eafa>", line 23, in <cell line: 23>
	    main(params, data, train_config)
	  File "<ipython-input-7-1a916b60d85b>", line 7, in main
	    trainer = get_trainer(params, data, seed, n_epochs)
	  File "<ipython-input-6-5f4795a7c81a>", line 31, in get_trainer
	    trainer = Trainer(
	  File "/usr/local/lib/python3.10/dist-packages/composer/trainer/trainer.py", line 1124, in __init__
	    self.engine.run_event(Event.INIT)
	  File "/usr/local/lib/python3.10/dist-packages/composer/core/engine.py", line 286, in run_event
	    self._run_loggers(event)
	  File "/usr/local/lib/python3.10/dist-packages/composer/core/engine.py", line 471, in _run_loggers
	    self._run_callbacks(event, loggers)
	  File "/usr/local/lib/python3.10/dist-packages/composer/core/engine.py", line 467, in _run_callbacks
	    cb.run_event(event, self.state, self.logger)
	  File "/usr/local/lib/python3.10/dist-packages/composer/core/callback.py", line 96, in run_event
	    return event_cb(state, logger)
	  File "/usr/local/lib/python3.10/dist-packages/composer/loggers/wandb_logger.py", line 205, in init
	    traceback.print_stack()
	```
	and second
	```python
	File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
	    return _run_code(code, main_globals, None,
	  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
	    exec(code, run_globals)
	  File "/usr/local/lib/python3.10/dist-packages/ipykernel_launcher.py", line 16, in <module>
	    app.launch_new_instance()
	  File "/usr/local/lib/python3.10/dist-packages/traitlets/config/application.py", line 992, in launch_instance
	    app.start()
	  File "/usr/local/lib/python3.10/dist-packages/ipykernel/kernelapp.py", line 619, in start
	    self.io_loop.start()
	  File "/usr/local/lib/python3.10/dist-packages/tornado/platform/asyncio.py", line 195, in start
	    self.asyncio_loop.run_forever()
	  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
	    self._run_once()
	  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
	    handle._run()
	  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
	    self._context.run(self._callback, *self._args)
	  File "/usr/local/lib/python3.10/dist-packages/tornado/ioloop.py", line 685, in <lambda>
	    lambda f: self._run_callback(functools.partial(callback, future))
	  File "/usr/local/lib/python3.10/dist-packages/tornado/ioloop.py", line 738, in _run_callback
	    ret = callback()
	  File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 825, in inner
	    self.ctx_run(self.run)
	  File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 786, in run
	    yielded = self.gen.send(value)
	  File "/usr/local/lib/python3.10/dist-packages/ipykernel/kernelbase.py", line 377, in dispatch_queue
	    yield self.process_one()
	  File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 250, in wrapper
	    runner = Runner(ctx_run, result, future, yielded)
	  File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 748, in __init__
	    self.ctx_run(self.run)
	  File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 786, in run
	    yielded = self.gen.send(value)
	  File "/usr/local/lib/python3.10/dist-packages/ipykernel/kernelbase.py", line 361, in process_one
	    yield gen.maybe_future(dispatch(*args))
	  File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 234, in wrapper
	    yielded = ctx_run(next, result)
	  File "/usr/local/lib/python3.10/dist-packages/ipykernel/kernelbase.py", line 261, in dispatch_shell
	    yield gen.maybe_future(handler(stream, idents, msg))
	  File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 234, in wrapper
	    yielded = ctx_run(next, result)
	  File "/usr/local/lib/python3.10/dist-packages/ipykernel/kernelbase.py", line 539, in execute_request
	    self.do_execute(
	  File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 234, in wrapper
	    yielded = ctx_run(next, result)
	  File "/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py", line 302, in do_execute
	    res = shell.run_cell(code, store_history=store_history, silent=silent)
	  File "/usr/local/lib/python3.10/dist-packages/ipykernel/zmqshell.py", line 539, in run_cell
	    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
	  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 2975, in run_cell
	    result = self._run_cell(
	  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3030, in _run_cell
	    return runner(coro)
	  File "/usr/local/lib/python3.10/dist-packages/IPython/core/async_helpers.py", line 78, in _pseudo_sync_runner
	    coro.send(None)
	  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3257, in run_cell_async
	    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
	  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3473, in run_ast_nodes
	    if (await self.run_code(code, result,  async_=asy)):
	  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
	    exec(code_obj, self.user_global_ns, self.user_ns)
	  File "<ipython-input-8-d36b8644eafa>", line 23, in <cell line: 23>
	    main(params, data, train_config)
	  File "<ipython-input-7-1a916b60d85b>", line 7, in main
	    trainer = get_trainer(params, data, seed, n_epochs)
	  File "<ipython-input-6-5f4795a7c81a>", line 31, in get_trainer
	    trainer = Trainer(
	  File "/usr/local/lib/python3.10/dist-packages/composer/trainer/trainer.py", line 1124, in __init__
	    self.engine.run_event(Event.INIT)
	  File "/usr/local/lib/python3.10/dist-packages/composer/core/engine.py", line 286, in run_event
	    self._run_loggers(event)
	  File "/usr/local/lib/python3.10/dist-packages/composer/core/engine.py", line 471, in _run_loggers
	    self._run_callbacks(event, loggers)
	  File "/usr/local/lib/python3.10/dist-packages/composer/core/engine.py", line 467, in _run_callbacks
	    cb.run_event(event, self.state, self.logger)
	  File "/usr/local/lib/python3.10/dist-packages/composer/core/callback.py", line 96, in run_event
	    return event_cb(state, logger)
	  File "/usr/local/lib/python3.10/dist-packages/composer/loggers/wandb_logger.py", line 205, in init
	    traceback.print_stack()
	```
	Most of the call stack can be ignored as it is related to running the code in a notebook. The important part of the first call stack is
	```python
	File "<ipython-input-8-d36b8644eafa>", line 23, in <cell line: 23>
	    main(params, data, train_config)
	  File "<ipython-input-7-1a916b60d85b>", line 7, in main
	    trainer = get_trainer(params, data, seed, n_epochs)
	  File "<ipython-input-6-5f4795a7c81a>", line 31, in get_trainer
	    trainer = Trainer(
	  File "/usr/local/lib/python3.10/dist-packages/composer/trainer/trainer.py", line 1124, in __init__
	    self.engine.run_event(Event.INIT)
	  File "/usr/local/lib/python3.10/dist-packages/composer/core/engine.py", line 286, in run_event
	    self._run_loggers(event)
	  File "/usr/local/lib/python3.10/dist-packages/composer/core/engine.py", line 471, in _run_loggers
	    self._run_callbacks(event, loggers)
	  File "/usr/local/lib/python3.10/dist-packages/composer/core/engine.py", line 467, in _run_callbacks
	    cb.run_event(event, self.state, self.logger)
	  File "/usr/local/lib/python3.10/dist-packages/composer/core/callback.py", line 96, in run_event
	    return event_cb(state, logger)
	  File "/usr/local/lib/python3.10/dist-packages/composer/loggers/wandb_logger.py", line 205, in init
	    traceback.print_stack()
	```
	and the second important part is
	```python
	File "<ipython-input-8-d36b8644eafa>", line 23, in <cell line: 23>
	    main(params, data, train_config)
	  File "<ipython-input-7-1a916b60d85b>", line 7, in main
	    trainer = get_trainer(params, data, seed, n_epochs)
	  File "<ipython-input-6-5f4795a7c81a>", line 31, in get_trainer
	    trainer = Trainer(
	  File "/usr/local/lib/python3.10/dist-packages/composer/trainer/trainer.py", line 1124, in __init__
	    self.engine.run_event(Event.INIT)
	  File "/usr/local/lib/python3.10/dist-packages/composer/core/engine.py", line 286, in run_event
	    self._run_loggers(event)
	  File "/usr/local/lib/python3.10/dist-packages/composer/core/engine.py", line 471, in _run_loggers
	    self._run_callbacks(event, loggers)
	  File "/usr/local/lib/python3.10/dist-packages/composer/core/engine.py", line 467, in _run_callbacks
	    cb.run_event(event, self.state, self.logger)
	  File "/usr/local/lib/python3.10/dist-packages/composer/core/callback.py", line 96, in run_event
	    return event_cb(state, logger)
	  File "/usr/local/lib/python3.10/dist-packages/composer/loggers/wandb_logger.py", line 205, in init
	    traceback.print_stack()
	```
	Three things to note here. 
	* The two different call stacks of `WandBLogger.init()` come from the first, successful call to `trainer` and the second, unsuccessful call to `trainer`. This means that both calls to `trainer` call `WandBLogger.init()` which in turn calls `wandb.init(**self._init_kwargs)`, the function that our error message says was never called. So why in the second call to `trainer` do we get the error message that `wand.init()` was never called if it was indeed called in `WandBLogger.init()`? Why does first call work while the second call fails -- the same functions seem to be called in both instances?
	* Both call stacks include the function `get_trainer` which defines the `trainer` object via `trainer.__init__()`. So perhaps the issue occurs in `trainer.__init__()` and is only detected when we call `trainer.fit()` . (Recall that the original error message says the error occurs while calling `training.fit()`.)
	* Third, this code runs on the event `Event.INIT`.  So poking around, I found this [code snippet](https://github.com/mosaicml/composer/blob/b6e2f55dd9f83afa2bc851a71f830c0874219fe2/composer/core/engine.py#L278) in `engine.py` which may be relevant:
	```python
	 if event == Event.INIT:
	            # For the INIT event, run the callbacks first to initialize the loggers
	            # For other events, run the algorithms first, so the callbacks have the state
	            # after algorithms modify it
	            self._check_for_still_open_callbacks()
	
	            # Run loggers first, so they can be initialized before any callbacks that may
	            # use them.
	            self._run_loggers(event)
	            self._run_nonlogger_callbacks(event)
	            traces = self._run_algorithms(event)
	```
	I wonder if this is where things may differ, as here is where the loggers are initialized. However, I'm not sure.

Moving forward, I still don't know why running the trainer with `WandBLogger` successfully runs the first time, but fails the second time `trainer.fit()` is called. I would like to fix this bug and would love any suggestions of how to investigate this further. Cheers!

# Environment

I called `composer_collect_env` in my notebook and pasted the output below:

Collecting system information...
---------------------------------
System Environment Report        
Created: 2023-07-05 17:02:14 UTC
---------------------------------

PyTorch information
-------------------
PyTorch version: 2.0.1+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.25.2
Libc version: glibc-2.31

Python version: 3.10.12 (main, Jun  7 2023, 12:45:35) [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.15.107+-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: Tesla T4
Nvidia driver version: 525.85.12
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          2
On-line CPU(s) list:             0,1
Thread(s) per core:              2
Core(s) per socket:              1
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           63
Model name:                      Intel(R) Xeon(R) CPU @ 2.30GHz
Stepping:                        0
CPU MHz:                         2299.998
BogoMIPS:                        4599.99
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       32 KiB
L1i cache:                       32 KiB
L2 cache:                        256 KiB
L3 cache:                        45 MiB
NUMA node0 CPU(s):               0,1
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Vulnerable; SMT Host state unknown
Vulnerability Meltdown:          Vulnerable
Vulnerability Mmio stale data:   Vulnerable
Vulnerability Retbleed:          Vulnerable
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Vulnerable: __user pointer sanitization and usercopy barriers only; no swapgs barriers
Vulnerability Spectre v2:        Vulnerable, IBPB: disabled, STIBP: disabled, PBRSB-eIBRS: Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm invpcid_single ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt arat md_clear arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.22.4
[pip3] pytorch-ranger==0.1.1
[pip3] torch==2.0.1+cu118
[pip3] torch-optimizer==0.3.0
[pip3] torchaudio==2.0.2+cu118
[pip3] torchdata==0.6.1
[pip3] torchmetrics==0.11.4
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.15.2
[pip3] torchvision==0.15.2+cu118
[conda] Could not collect

Composer information
--------------------
Composer version: 0.15.0
Composer commit hash: None
Host processor model name: Intel(R) Xeon(R) CPU @ 2.30GHz
Host processor core count: 1
Number of nodes: 1
Accelerator model name: Tesla T4
Accelerators per node: 1
CUDA Device Count: 1

**Comment by eracah** [comment]
Hi @ez2rok, interesting bug find! I can't quite pinpoint the exact root cause of the issue, but I believe the issue is you never called `trainer.close()` after `trainer.fit()` before creating a new trainer. Give that a try and see if that fixes your issue.

**Comment by ez2rok** [comment]
Haha, wow adding `trainer.close()` fixed the entire problem! Seems like magic, but it works now. Thanks!

**Comment by ez2rok** [comment]
Looking into things a bit further, `trainer.close()` calls `engine.close()` which eventually calls `WandBLogger.post_close()` which calls `wandb.finish()`. And it seems like calling `wandb.finish()` clears up the issue. 

Cheers!

**Comment by eracah** [comment]
Great! Glad to hear it worked, @ez2rok ! I will close for now. Feel free to let us know if you have any other issues
