### ISSUE TITLE
Enabling HYBRID_SHARD and _HYBRID_SHARD_ZERO2 of torch.distributed.fsdp.ShardingStrategy

### ISSUE THREAD

**Issue by hiroshi-matsuda-rit** [mosaicml/composer#2401]
## 🚀 Feature Request

Add `HYBRID_SHARD` and `_HYBRID_SHARD_ZERO2` options in [sharding_map](https://github.com/mosaicml/composer/blob/aaa8dcc4cdf7d98a4584b043e0090338072655cd/composer/trainer/mosaic_fsdp.py#L35).

## Motivation

By specifying `ShardingStrategy.HYBRID_SHARD` or `ShardingStrategy._HYBRID_SHARD_ZERO2` in FSDP, it is possible to minimize the decrease in training throughput when the interlinks between the nodes are slow.

From [pytorch repo](https://github.com/pytorch/pytorch/blob/c9edf1107313b04ccaf0c414df3465808fbcb1d9/torch/distributed/fsdp/api.py#L32
):

```
    - ``HYBRID_SHARD``: Apply ``FULL_SHARD`` within a node, and replicate parameters across
      nodes. This results in reduced communication volume as expensive all-gathers and
      reduce-scatters are only done within a node, which can be more performant for medium
      -sized models.
    - ``_HYBRID_SHARD_ZERO2``: Apply ``SHARD_GRAD_OP`` within a node, and replicate parameters across
      nodes. This is like ``HYBRID_SHARD``, except this may provide even higher throughput
      since the unsharded parameters are not freed after the forward pass, saving the
      all-gathers in the pre-backward.
```

## [Optional] Implementation

Adding two lines below to `sharding_map` in `composer/trainer/mosaic_fsdp.py`:

```
    'HYBRID_SHARD': ShardingStrategy.HYBRID_SHARD,
    '_HYBRID_SHARD_ZERO2': ShardingStrategy._HYBRID_SHARD_ZERO2,
```

## Additional context

Actually, we're getting `IndexError: list assignment index out of range` while saving the checkpoint if we use `HYBRID_SHARD` or `_HYBRID_SHARD_ZERO2`.

```
2023-07-29 11:30:00,381: rank0[29907][MainThread]: DEBUG: composer.utils.checkpoint: Saving checkpoint to mpt-1b_2x8gpu_hybrid_zero2.max_batch/ep{epoch}-ba{batch}-rank{rank}.pt
Traceback (most recent call last):
  File "/model/mosaicml/llm-foundry/scripts/train/train.py", line 355, in <module>
    main(cfg)
  File "/model/mosaicml/llm-foundry/scripts/train/train.py", line 344, in main
    trainer.fit()
  File "/model/mosaicml/llm-foundry/scripts/venv/lib/python3.10/site-packages/composer/trainer/trainer.py", line 1804, in fit
    self._train_loop()
  File "/model/mosaicml/llm-foundry/scripts/venv/lib/python3.10/site-packages/composer/trainer/trainer.py", line 2035, in _train_loop
    self.engine.run_event(Event.BATCH_CHECKPOINT)
  File "/model/mosaicml/llm-foundry/scripts/venv/lib/python3.10/site-packages/composer/core/engine.py", line 293, in run_event
    self._run_nonlogger_callbacks(event)
  File "/model/mosaicml/llm-foundry/scripts/venv/lib/python3.10/site-packages/composer/core/engine.py", line 475, in _run_nonlogger_callbacks
    self._run_callbacks(event, callbacks)
  File "/model/mosaicml/llm-foundry/scripts/venv/lib/python3.10/site-packages/composer/core/engine.py", line 467, in _run_callbacks
    cb.run_event(event, self.state, self.logger)
  File "/model/mosaicml/llm-foundry/scripts/venv/lib/python3.10/site-packages/composer/core/callback.py", line 96, in run_event
    return event_cb(state, logger)
  File "/model/mosaicml/llm-foundry/scripts/venv/lib/python3.10/site-packages/composer/callbacks/checkpoint_saver.py", line 346, in batch_checkpoint
    self._save_checkpoint(
  File "/model/mosaicml/llm-foundry/scripts/venv/lib/python3.10/site-packages/composer/callbacks/checkpoint_saver.py", line 384, in _save_checkpoint
    saved_path = checkpoint.save_checkpoint(
  File "/model/mosaicml/llm-foundry/scripts/venv/lib/python3.10/site-packages/composer/utils/checkpoint.py", line 562, in save_checkpoint
    'state': state.state_dict(),
  File "/model/mosaicml/llm-foundry/scripts/venv/lib/python3.10/site-packages/composer/core/state.py", line 861, in state_dict
    fsdp_get_optim_state_dict(self.model, optimizer, state_dict_type=self.fsdp_state_dict_type)
  File "/model/mosaicml/llm-foundry/scripts/venv/lib/python3.10/site-packages/composer/core/state.py", line 146, in fsdp_get_optim_state_dict
    optim_state_dict = FSDP.optim_state_dict(model, optim)  # type: ignore
  File "/model/mosaicml/llm-foundry/scripts/venv/lib/python3.10/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 1753, in optim_state_dict
    return FullyShardedDataParallel._optim_state_dict_impl(
  File "/model/mosaicml/llm-foundry/scripts/venv/lib/python3.10/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 1154, in _optim_state_dict_impl
    return _optim_state_dict(
  File "/model/mosaicml/llm-foundry/scripts/venv/lib/python3.10/site-packages/torch/distributed/fsdp/_optim_utils.py", line 1455, in _optim_state_dict
    _gather_orig_param_state(
  File "/model/mosaicml/llm-foundry/scripts/venv/lib/python3.10/site-packages/torch/distributed/fsdp/_optim_utils.py", line 1690, in _gather_orig_param_state
    gathered_state = _all_gather_optim_state(fsdp_state, optim_state)
  File "/model/mosaicml/llm-foundry/scripts/venv/lib/python3.10/site-packages/torch/distributed/fsdp/_optim_utils.py", line 1595, in _all_gather_optim_state
    dist.all_gather_object(object_list, processed_state)
  File "/model/mosaicml/llm-foundry/scripts/venv/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1451, in wrapper
    return func(*args, **kwargs)
  File "/model/mosaicml/llm-foundry/scripts/venv/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2072, in all_gather_object
    object_list[i] = _tensor_to_object(tensor, tensor_size)
IndexError: list assignment index out of range
```

**Comment by mvpatel2000** [comment]
Sorry we missed this earlier! This is. on our roadmap, and we will add support in a month or so. If you have a more immediate need, we're happy to help you out more.

**Comment by eracah** [comment]
HI @hiroshi-matsuda-rit, I'm curious what you set `state_dict_type` to in `fsdp_config` ? Can I see your script where you instantiated the `Trainer` object?

**Comment by eracah** [comment]
hi @hiroshi-matsuda-rit, we were able to save and resume from checkpoints the `HYBRID_SHARD` sharding strategy using pytorch 2.1. Which version of pytorch were you using?

**Comment by hiroshi-matsuda-rit** [comment]
hi @eracah, It's so great that the HYBRID_SHARD is working with llm-foundry. We used torch==2.0.1+cu118 for the llm-foundry evaluation.

**Comment by eracah** [comment]
yay great to hear!

**Comment by eracah** [comment]
HYBRID_SHARD is no supported in Composer and works with PyTorch 2.1
