### ISSUE TITLE
Fix checkpointing when saving checkpoints locally

### ISSUE THREAD

**Issue by ajaysaini725** [mosaicml/composer#276]
** Environment **
Composer v0.3.1

** To reproduce

1. Run training and save a checkpoint locally. Use the defaults and don't specify a checkpoint folder or run directory. The checkpoint will be saved in something like `runs/[timestamp]/checkpoints/checkpoint_filename.tar`
2. Run training and provide that file path as the path to load a checkpoint from. You will consistently get the following error (regardless of network):

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/pin_memory.py", line 28, in _pin_memory_loop
    r = in_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 116, in get
    return _ForkingPickler.loads(res)
  File "/usr/local/lib/python3.8/dist-packages/torch/multiprocessing/reductions.py", line 289, in rebuild_storage_fd
    fd = df.detach()
  File "/usr/lib/python3.8/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/usr/lib/python3.8/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 508, in Client
    answer_challenge(c, authkey)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 752, in answer_challenge
    message = connection.recv_bytes(256)         # reject large message
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
```

## Expected behavior

Loading from a local checkpoint file should work correctly.

**Comment by moinnadeem** [comment]
Weird, I've been using checkpointing correctly this whole time (and even from local disk). My branch might be stale off of dev by 2-3 days though

**Comment by ravi-mosaicml** [comment]
Can you share the logs form the logs folder?

**Comment by ravi-mosaicml** [comment]
I don't think this is a checkpointing issue -- the error is likely coming from a data loader worker. From the stack trace, it looks very similar to this one https://github.com/pytorch/pytorch/issues/1551.

Going to close the issue...but please re-open it if you are still running into it on the latest dev version of composer (and please share the exact command being run)
