### ISSUE TITLE
Trainer crashes when using FP16 + DeepSpeed

### ISSUE THREAD

**Issue by jbloxham** [mosaicml/composer#968]
```
Traceback (most recent call last):
  File "/home/mosaicml/composer/examples/run_composer_trainer.py", line 66, in <module>
    main()
  File "/home/mosaicml/composer/examples/run_composer_trainer.py", line 62, in main
    trainer.fit()
  File "/home/mosaicml/composer/composer/trainer/trainer.py", line 979, in fit
    self._train_loop()
  File "/home/mosaicml/composer/composer/trainer/trainer.py", line 1118, in _train_loop
    total_loss = self._train_batch(use_grad_scaling)
  File "/home/mosaicml/composer/composer/trainer/trainer.py", line 1217, in _train_batch
    total_loss = self._train_microbatches(microbatches)
  File "/home/mosaicml/composer/composer/trainer/trainer.py", line 1295, in _train_microbatches
    self._train_microbatch(use_grad_scaling, current_batch_size, total_loss, is_final_microbatch)
  File "/home/mosaicml/composer/composer/trainer/trainer.py", line 1333, in _train_microbatch
    with get_precision_context(self.state.precision):
  File "/usr/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/home/mosaicml/composer/composer/core/precision.py", line 60, in get_precision_context
    raise ValueError(f"Unsupported precision: {precision}")
ValueError: Unsupported precision: Precision.FP16
```

**Comment by hanlint** [comment]
This looks to have been introduced in https://github.com/mosaicml/composer/pull/832 which refactored the `precision_context` manager code, but did not catch the `FP16` case.
